# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab1915c891067fb1d44c6ea50ac91b479b1802fa66146da0f8711a115f1676ab054c99e92a1c33faf547eb6de68c9fdac91fb9a80b765b11b9a9690a8aa7c78

test:
  secret_key_base: 23eb5c1ba64da0b52941b9d73cb6e5c6468cac5969d25a8d798c0ff4a52f1ba075864174ae35340c0f5bc87608d5788e67175a70771bf8b9171e7689a9c9ed00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
